### PR TITLE
Es updated customer ctrland view

### PR DESCRIPTION
**Pull request by estorms**
Code updates:
1. Overloaded Create(Customer customer) method in customers controller reintroduced to allow addition of new customer to database 
2. Display attributes added to Customer model

To test:

Git fetch
Git checkout es-updatedCustomerCtrlandView
Dotnet run 
Navigate to Customers/Create
Fill in form & click "Create" button
Check that new customer has been added to database

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm!

**Comment by ewilliamswtn** [comment]
tested, womm

**Pull request merged**
