### PR TITLE
Alphabranch

### PR DESCRIPTION
**Pull request by lairdhousehold**
Product list and Types list are now alphabetical

To Test go to 

git fetch
git checkout alphabranch 
dotnet run 
go to 
- url: http://localhost:5000/  These product names are now listed alphabetically
-url : http://localhost:5000/Products/Types Categories are now listed alphabetically

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by estorms** [comment]
WOMM

**Comment by davidyunker** [comment]
WOMM

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
