### PR TITLE
Fw order view model

### PR DESCRIPTION
**Pull request by flawavi**
Added OrderViewModel.cs

To Test:

git fetch
git checkout fw-orderViewModel
check the OrderViewModel in the ViewModels folder and make sure nothing else is needed, and nothing that exists is unnecessary.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
lgtm

**Comment by ewilliamswtn** [comment]
👍

**Comment by estorms** [comment]
WOMM

**Comment by davidyunker** [comment]
lgtm

**Comment by ewilliamswtn** [comment]
👍  revised

**Comment by estorms** [comment]
lgtm

**Comment by lairdhousehold** [comment]
rewomm

**Pull request merged**
