### PR TITLE
Added logic to add new customer to dropdown/text link on new customer…

### PR DESCRIPTION
**Pull request by davidyunker**
… creation

Added to the overloaded Create() method on the CustomersController so that the Create Account link changes to the name of the new customer on creation. 

Method: Create () 
Controller: CustomersController 

TO TEST: 
git fetch 
git checkout dy-activecustomerNew 
dotnet run 
Click Create Account, create a new user and the Create Account link should change.

### CODE REVIEW

**Comment by estorms** [comment]
WOMM!

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
nice! 👍

**Comment by flawavi** [comment]
womm

**Pull request merged**
