### PR TITLE
Database seeding, minor styling on home page

### PR DESCRIPTION
**Pull request by ewilliamswtn**
- Added `Data/DbInitializer.cs` file, which seeds 25 Product items to the database.  
- Added a `.productRow` class to Product rows in `Views/Products/Index.cshtml`
- Added styling to the `.productRow` class:  small bottom margin, to add separation between product descriptions
-  Called `DbInitializer.Initialize(app.ApplicationServices)`, to initialize seeding, in  `Startup.cs`
##### Accessing branch:
- git fetch
- git checkout origin/ewSeedDb
##### Features to check:
- 25 products are populated on the home screen
- There is spacing between rows
##### Notes

You must delete all data in your local database to work.  The easiest way is most likely doing it manually: 
- Open your database.  Select the **Browse Data** tab.
- Select **Product** under the Table dropdown.
- Click on any cell for the product you wish to delete.
- Click the **Delete Record** button.
- Repeat until all products are removed.
- Repeat for **Customer** table and **ProductType** tables (and any other tables that happen to have data, not including **_EFMigrationsHistory** and **sqlite_sequence**)
- When all data is deleted, click the **Write Changes** button at the top of your database.

### CODE REVIEW

**Comment by davidyunker** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
