### PR TITLE
added row class to div on types.cshtml

### PR DESCRIPTION
**Pull request by flawavi**
added row class to div in types.cshtml so that the horizontal rule would show up on all viewport sizes.

git fetch
git checkout fw-footer
navigate to categories page and check to make sure that horizontal rule is visible on all sizes of your browser, and make sure that the footer itself is below the HR.

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
👍

**Comment by estorms** [comment]
lgtm!

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Pull request merged**
