### PR TITLE
Es productlistduplicatecountfixed

### PR DESCRIPTION
**Pull request by estorms**
Details:

When a user navigates to the Order/Cart view, he/she now sees each product in his/her cart listed only once, with a number in parentheses beside that product indicates its quantity, rather than duplicate listings of the same product.

To test:

1. Git fetch
2. Checkout `es-PRODUCTLISTDUPLICATECOUNT`
3. Select a customer with duplicate items in the cart and navigate to the Order/Cart view
4. Insure that the product count beside each item is accurate
5. Select a payment type and submit order
6. Ensure app still routes to order confirmation page

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍  wom wai lgtm rip hrc lol #trump2016

**Comment by flawavi** [comment]
womm level: jerome

**Comment by davidyunker** [comment]
womm

**Pull request merged**
