### PR TITLE
Fw es subcategoriesordered

### PR DESCRIPTION
**Pull request by estorms**
Details:

1. When selecting a subcategory link in the products/types view, the user now routes to a list of all the products in that subcategory.

2. Then, when the user clicks on a single product, he/she is routed to that product's detail view.

To test:

1. Git fetch
2. Git checkout fw-es-subcategoriesordered
3. Select "categories" from the navbar.
4. Select a subcategory from the types view.
5. Select a product below one of the subcategory headings.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by davidyunker** [comment]
Much womm.

**Comment by flawavi** [comment]
wommmmm womm wom wom WOOMMMMM

**Pull request merged**
