### PR TITLE
Es products detail bug fix

### PR DESCRIPTION
**Pull request by estorms**
Detail() method in products controller adjusted to instantiate ProductDetail viewmodel class and pass in selected product id.

To test:
1. Git fetch
2. Git checkout es-products-detail-bug-fix
3. Dotnet run to render homepage
4. Select the hyperlink on a product name and ensure its details view renders correctly

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍 👍 👍

**Comment by flawavi** [comment]
womm

**Comment by estorms** [comment]
Pull request on es-dropdown fix contains these code updates; removing duplicate PR

**Pull request closed without merging**
