### PR TITLE
Es product detail viewmodel

### PR DESCRIPTION
**Pull request by estorms**
Product Detail View Model created. 

This class inherits from BaseViewModel and contains a property of type Product; this will be the product whose details are displayed on the page.

This class also contains a custom constructor that passes the current BangazonContext db session up to the BaseViewModel every time class is instantiated.

To test:
1. Git fetch
2. Git checkout es-product-detail-viewmodel
3. Navigate to ViewModels/ProductDetailViewModel.cs
4. Check for methods and properties described above

### CODE REVIEW

**Comment by flawavi** [comment]
wai

**Comment by davidyunker** [comment]
wai, just needs additional documentation for Def of Done.

**Comment by lairdhousehold** [comment]
wai

**Comment by ewilliamswtn** [comment]
wai 👍

**Pull request merged**
