### PR TITLE
Es activate method customer controller

### PR DESCRIPTION
**Pull request by estorms**
Annotations and three new methods added to customer controller:
1. Menu() - creates a new instance of the MenuViewModel class and passes in the current BangazonContext as argument in order to extract existing customers from corresponding db table
2. Activate() - responds to POST method from Site.js by creating a new instance of the ActiveCustomer class. This method accepts an argument of CustomerId, of type integer, and uses it to traverse the customers table in the db and attach the selected customer as the Customer property on the instance of the ActiveCustomer class. This method returns an object with key/value pair result:true
3. Error() - returns the Error View

To test: 
1. Git fetch 
2. Checkout branch es-activate-method-customer-controller
3. Review CustomerController.cs for above methods

### CODE REVIEW

**Comment by davidyunker** [comment]
WOMM

**Comment by ewilliamswtn** [comment]
wai (works as intended) 😄

**Comment by flawavi** [comment]
wai

**Comment by lairdhousehold** [comment]
wai

**Pull request merged**
