### PR TITLE
uncommented link in active customer component

### PR DESCRIPTION
**Pull request by estorms**
Uncommented link for display below dropdown in navbar

To test:

1. Git fetch
2. Git checkout es-uncommented-link
3. Ensure "create account" displays below dropdown menu
4. Select "create account" and ensure app routes to Customers/Create form

### CODE REVIEW

**Comment by flawavi** [comment]
womm y'all

**Comment by davidyunker** [comment]
much womm.

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
