### PR TITLE
styling for cart view

### PR DESCRIPTION
**Pull request by ewilliamswtn**
## Changes
Cart View now has a left and right column.  The left column is for the the the name, price, and quantity of each item in the cart, as well as the total price.  The right column is for the payment dropdown, new payment button, and the submit order button.  The right column will be pulled below the left column at screen width 768px and below.

## To Test
- ```git fetch```
- ```git checkout ew-CartStyle```
- Select a Bangazon Customer and make sure there are items in your cart
- Navigate to the Cart View.  Make sure the styling looks good, and fits the description above

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by davidyunker** [comment]
lgtm

**Comment by estorms** [comment]
lgtm

**Comment by lairdhousehold** [comment]
lgtm

**Pull request merged**
