### PR TITLE
number of products in subcategory now registering on types view

### PR DESCRIPTION
**Pull request by estorms**
Details:

1. Number of products in each subcategory now registers on the Products/Types view.

To test:

1. Git fetch
2. Git checkout es-take2NumProducts
3. Navigate to Products/Types view
4. Be sure that each product subcategory displays the number of items in that particular category

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by davidyunker** [comment]
WOMM. (I see numbers!) (NUMBERS)

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Pull request merged**
