### PR TITLE
product detail view displays name only if chosen customer exists

### PR DESCRIPTION
**Pull request by estorms**
Modified product detail view to reflect chosen customer's name only if a customer has been selected from dropdown.

To test:

1. Git fetch
2. Git checkout es-modifie-d-product-detail
3. Dotnet run
4. Check that customer name only displays on product detail view if customer has been chosen from the dropdown menu

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm!

**Pull request merged**
