### PR TITLE
Order confirm now works from Submit Order button

### PR DESCRIPTION
**Pull request by davidyunker**
Files changed:
Controllers/OrderController.cs
Views/Order/Confirm.cshtml

Confirm method adjusted 

TO TEST:
git fetch 
git checkout dy-OrderConfirm 

Select a customer 
Click on their name to go to their cart 
click the Submit Order button 
it should take to the Order/Confirm view. 
(Still more work to be done to clear out the order, etc.)

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
