### PR TITLE
validation for creating customer and products now working

### PR DESCRIPTION
**Pull request by davidyunker**
Forms to create a new customer and a new product now display error messages when all the fields aren't filled out. 

Files updated: 
Controllers/CustomerController.cs 
Views/Customers/Create.cshtml 
Views/Products/Create.cshtml 
Views/Shared/_Layout.cshtml

TO TEST:
git fetch 
git checkout dy-validate 

1. attempt to create a customer and don't fill out a field. You should get an error message at the top detailing the error.
2. attempt to add a product and don't fill out a field. You should get an error message at the top detailing the error.

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Pull request merged**
