### PR TITLE
Dy menu view model

### PR DESCRIPTION
**Pull request by davidyunker**
MenuViewModel will inherit from BaseViewModel and store the instance of ActiveCustomer created in BaseViewModel for display on the DOM (in navbar and injected via _Layout.cshtml file) as "First Name, Last Name (#ofItemsInCart).

_If not created, BaseViewModel and ActiveCustomer class will need to be created in order for the MenuViewModel to function._

The _layout file is modified to inject "ActiveCustomerComponent" into navbar.

The ActiveCustomerComponent.cshtml file was created in the Shared folder.

TO TEST: 
1. git fetch
2. git checkout dy-MenuViewModel 
3. check the MenuViewModel.cs file (in the ViewModel folder) 
4. check the ActiveCustomerComponent.cshtml file in the Shared folder 
5. check the _Layout.cshtml file in the Shared folder.  

Ref: https://github.com/NSSNamespace/Initial_Bangazon_Site/issues/51

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
👍

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
