### PR TITLE
Customer's cart now displaying items

### PR DESCRIPTION
**Pull request by davidyunker**
Files modified:

Controllers/OrderController.cs
Models/Product.cs
ViewModels/OrderViewModel.cs
Views/Order/Cart.cshtml

TO TEST: 
git fetch 
git checkout dy-OrderCartItems 

Choose an active customer, then go to the list of items. 

Add some items to your cart. 

Then click on your name. 

The name should take you to the list of their cart.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by ewilliamswtn** [comment]
```
  <div class="row">
    <div class="col-md-4">

      <a asp-action="Detail" asp-route-id="@product.ProductId" asp-controller="Products">
        @Html.DisplayFor(modelItem => product.Title)
      </a>
    </div>
    <div class="col-md-4">@Html.DisplayFor(modelItem => product.Description)</div>
    <div class="col-md-4">@Html.DisplayFor(modelItem => product.Price)</div>
</div>
}
<div class="row">
  <div class="col-md-6">
    <strong>Cart Total:</strong> $@Model.CartTotal
  </div>
</div>

<div class="row text-right">
 <a asp-action="Confirm" class="btn btn-danger btn-lg">Submit Order</a>
</div>
```

**Comment by ewilliamswtn** [comment]
The code linked above, if used to replace line 17 and below of `Views/Order/Cart.cshtml`, would make the following changes:
- The hyperlink for the product's title now works properly
- The product title, description, and price are now put into bootstrap columns (as opposed to just the title)
- The submit order button is moved to the bottom of the order form

**Comment by flawavi** [comment]
womm

**Comment by estorms** [comment]
womm

**Pull request merged**
