### PR TITLE
wrote ajax post call for dropdown menu where user selects themselves …

### PR DESCRIPTION
**Pull request by flawavi**
…as active customer.

Simple ajax post request from browser to our backend. We take the CustomerId that is sent and pass it to our Activate method on the CustomerController to make that selected customer the active customer on the site.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Comment by estorms** [comment]
womm

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
