### PR TITLE
Es active customer class

### PR DESCRIPTION
**Pull request by estorms**
Active customer class created. Contains:
1. A private property ("_instance") that holds one instance of the ActiveCustomer class itself.
2. A public property ("instance") that returns the private property of "_instance" if that private property has not yet been created
3. A public property of type Customer called "Customer"

To test: 
1. Git fetch
2. Checkout branch origin es-active-customer-class
3. Review Data/ActiveCustomer.cs file for above properties

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
