### PR TITLE
changed viewdata in types.cshtml to read 'categories' instead of prod…

### PR DESCRIPTION
**Pull request by flawavi**
…uct type listing.

git fetch
git checkout fw-types-cshtml-heading
navigate to the categories view
make sure the heading at the top is "Categories"
womm

### CODE REVIEW

**Comment by davidyunker** [comment]
womm

**Comment by estorms** [comment]
WOMM

**Comment by ewilliamswtn** [comment]
👍

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
