### PR TITLE
set CustomerId to 0 in basefview model and then checked against that …

### PR DESCRIPTION
**Pull request by flawavi**
…in if statement in layout.

To Test:

git fetch
git checkout fw-hide-sellsomething-link
do not set active user
make sure that sell something link does not appear.
set an active user and make sure that the sell something link appears.

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
👍

**Comment by estorms** [comment]
WOMM

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Pull request merged**
