### PR TITLE
Es dropdownfix

### PR DESCRIPTION
**Pull request by estorms**
Contains two changes to products controller:
1. Detail() method in products controller adjusted to instantiate ProductDetail viewmodel class and pass in selected product id.
2. Index() method updated to include CustomerId dropdown in navbar

To test:
1. Git fetch
2. Git checkout es-dropdownfix
3. Dotnet run to render homepage
4. Check that homepage includes dropdown with customer names
5. Select the hyperlink on a product name and ensure its details view renders correctly and includes dropdown with customer names

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
👍  👏

**Comment by lairdhousehold** [comment]
👍

**Comment by flawavi** [comment]
womm

**Comment by davidyunker** [comment]
WOMM

**Pull request merged**
