### PR TITLE
Number of items in cart now displaying

### PR DESCRIPTION
**Pull request by davidyunker**
Files modified:
ViewModels/BaseViewModel.cs 
Views/Shared/ActiveCustomerComponent.cshtml

TO TEST:
git fetch 
git checkout dy-NumberOfItemsInCart 

choose an active customer 
if the customer has items in their cart that number should display in the () next to the shopping cart icon

### CODE REVIEW

**Comment by flawavi** [comment]
There's an unnecessary closing parens on line 19 in the active customer component file. it's showing up next to the shopping cart.

**Comment by flawavi** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by estorms** [comment]
LGTM

**Pull request merged**
