### PR TITLE
updated login in product-detail-view, added default message for new c…

### PR DESCRIPTION
**Pull request by estorms**
Details:

Updated if-block on product detail view so personalized message displays based on CustomerId, rather than name; added else statement directing customers who have not create an account to do so in order to purchase a product.

To test:

1. Git fetch
2. Git checkout es-fix-product-detail-view-logic
3. Select a product from the home page both before and after selecting a customer from the dropdown menu

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by flawavi** [comment]
womm

**Comment by davidyunker** [comment]
WOMM AND LGTM.

**Comment by ewilliamswtn** [comment]
👍

**Pull request merged**
