### PR TITLE
added BaseViewModel and added notes on what is occuring in the model

### PR DESCRIPTION
**Pull request by davidyunker**
BaseViewModel created with the following: 
IEnumerable collection of SelectListItems that contains CustomerId (defined herein as First Name, Last Name)

Logic that creates a new instance of the Active Customer class and associates the chosen customer (as received from ajax post from Site.js) with the CustomerId received in post

Base view model constructor that passes in Bangazon context so that CustomerId's can be added to dropdown list. 

STEPS TO TEST: 
git fetch
git checkout dy-BaseViewModel 

Ref: https://github.com/NSSNamespace/Initial_Bangazon_Site/issues/49

### CODE REVIEW

**Comment by estorms** [comment]
womm

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm 
waiting for ActiveCustomer class

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
