### PR TITLE
Dy productsby type list

### PR DESCRIPTION
**Pull request by davidyunker**
Users can now click on the categories and get a list of products. 

Files changed:
Controllers/ProductsController.cs
Views/Products/Type.cshtml
Views/Products/Types.cshtml

TO TEST: 
git fetch
git checkout dy-ProductsbyTypeList 
dotnet run 

Click on Categories from the navbar
Then click on any of the categories 
The list of products of that category should display!

### CODE REVIEW

**Comment by flawavi** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍

**Comment by estorms** [comment]
WOMM!

**Comment by lairdhousehold** [comment]
rewomm

**Pull request merged**
