### PR TITLE
link to product listing at bottom of Create Customer View now works

### PR DESCRIPTION
**Pull request by estorms**
Details:

Link "Back to product listing" at bottom of Create Customer view now works.

To test:

1. Git fetch
2. checkout es-customer-controller-updates
3. Select "create account" link from navbar
4. Select "Back to product listing" link and ensure page routes to homepage/product list view

### CODE REVIEW

**Comment by ewilliamswtn** [comment]
👍

**Comment by flawavi** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
