### PR TITLE
css changed, footer now behaves properly

### PR DESCRIPTION
**Pull request by ewilliamswtn**
## Changes:
**site.css:** gave ```.container``` class relative positioning, and ```footer``` absolute positioning and a bottom offset.  This should ensure the footer follows page content, regardless of content size or browser size.

## To test:
```git fetch```
```git checkout origin/ewFooter```

Make sure footer properly is rendered below the page content on all page views.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by estorms** [comment]
WOMM!

**Comment by davidyunker** [comment]
Looks a little cramped on the Categories page on my computer. Everything else looks good!

**Comment by flawavi** [comment]
womm

**Pull request merged**
