### PR TITLE
Ew test3

### PR DESCRIPTION
**Pull request by ewilliamswtn**
Mostly cosmetic/convenience changes to facilitate product demo.  Please excuse the non-descriptive name, this branch was created with the intention of being a test.
- `Models/Product.cs`: changed `Price` property from a double to a decimal.  Currency should be stored as a decimal.
- `Views/Products/Index.cshtml`: reformatted the way products are displayed.  Product properties are listed in rows, displaying `Title`, `Price`, and `Descpription`, with `Title` being a hyperlink to the `ProductDetail` view
- `Views/Shared/_Layout.cshtml`:  updated navbar links so that they properly send a user to the page that was selected.  The _User Dropdown_ will route a user back to the homepage, as this is a placeholder, for the time being.
- Changed css for the product's price column on the homepage.  Price is now centered, as opposed to left aligned.  Left aligned is counterintuitive for displaying a money value.  If a user was viewing a product that costs $1 , and a product costing $1000 was just below it, both **1**'s would line up, with the **0**'s and decimals trailing after.  It is better to have these values **not** line up, as to not have a value in the one's place aligned with a value in the thousands place, etc.

### CODE REVIEW

**Comment by estorms** [comment]
womm

**Comment by ewilliamswtn** [comment]
wom wom wom

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Comment by flawavi** [comment]
nom nom womm womm

**Pull request merged**
