### PR TITLE
created the Order model

### PR DESCRIPTION
**Pull request by davidyunker**
As part of the setup of Bangazon, I have created the Order model. 

Ref: https://github.com/NSSNamespace/Initial_Bangazon_Site/issues/9

### CODE REVIEW

**Comment by lairdhousehold** [comment]
lgmt

**Comment by estorms** [comment]
lgtm

**Comment by flawavi** [comment]
lgtm

**Comment by lairdhousehold** [comment]
lgtm

**Comment by ewilliamswtn** [comment]
lgtm

**Comment by flawavi** [comment]
lgtm

**Comment by lairdhousehold** [comment]
lgtm

**Pull request merged**
