### PR TITLE
Es order date completed

### PR DESCRIPTION
**Pull request by estorms**
Details:

1. Site.js now has listener on confirm button in order to send patch request to order controller/confirm method

2. Order controller now contains a method to patch the order in database once customer clicks confirm button

3. Order controller now contains a method to route the user to confirmation view once patch in database has been completed

To test:

1. Git fetch
2. Git checkout es-order-date-completed
3. Select the cart icon for an active customer
4. Hit "complete" button in cart view
5. Be sure that order now has date completed property in database
6. Be sure that view routes to confirmation page thanking user for his/her order

### CODE REVIEW

**Comment by davidyunker** [comment]
So much WOMM. Very Empty Cart after button press

**Comment by ewilliamswtn** [comment]
☝️ what he said 👍 👍

**Comment by flawavi** [comment]
somebody call the WOMMBULANCE!

**Comment by lairdhousehold** [comment]
womm

**Pull request merged**
