### PR TITLE
create product method now accepts active customer id and posts new pr…

### PR DESCRIPTION
**Pull request by estorms**
…oduct to database

Details:

1. Create product method now accepts active customer's id as part of product object sent to database

2. Totally rocks.

To test:

1. Git fetch
2. checkout team-createProductMethod
3. Choose customer from dropdown menu
4. Post product to database and check customer id

### CODE REVIEW

**Comment by flawavi** [comment]
WOMM ON YOU CRAZY DIAMOND

**Comment by lairdhousehold** [comment]
wommmm

**Comment by davidyunker** [comment]
SO MUCH WOMM.

**Comment by ewilliamswtn** [comment]
womm

**Pull request merged**
