### PR TITLE
got the Create Customer View to work with the amazing, wonderful and …

### PR DESCRIPTION
**Pull request by davidyunker**
…not at all frustrating dropdown

Added a CreateCustomerViewModel, which inherits from the BaseViewModel 

CreateCustomerViewModel works with the Create.cshtml in the Views/Customers folder to display the fields necessary to create a customer. 

TO TEST: 
git fetch 
git checkout dy-wtf

### CODE REVIEW

**Comment by estorms** [comment]
WOMM! Love it. :)

**Comment by ewilliamswtn** [comment]
☝️  what she said

**Comment by flawavi** [comment]
WOOOOOOMMMMMMMMMMMMMM

**Comment by lairdhousehold** [comment]
woom 💯

**Pull request merged**
